
language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules

install:
  - npm install -g dredd
  - npm install

script:
  - export FLOW_BROKER_URL=http://127.0.0.1:3030
  - export DEVICE_MANAGER_URL=http://127.0.0.1:3030
  - export CRON_URL=http://127.0.0.1:3030/cron
  - bash start-test.sh

after_success:
  - chmod +x travis/publish.sh
  - chmod +x travis/deploy-gh-pages.sh
  - docker build -t ${TRAVIS_REPO_SLUG} -f DockerFile .
  - travis/publish.sh
  - travis/deploy-gh-pages.sh

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: ${TRAVIS_BRANCH}